// ROOMS
export const CREATE_NEW_ROOM = 'CREATE_NEW_ROOM';
export const ADD_ROOM = 'ADD_ROOM';
export const LOADING_ROOM = 'LOADING_ROOM';
export const ERROR_ADDING_ROOM = 'ERROR_ADDING_ROOM';

// MESSAGES
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ERROR_ADDING_MESSAGE = 'ERROR_ADDING_MESSAGE';
